# Generated by Django 4.0.5 on 2022-06-22 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0002_rename_reolcol_user_rolecol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clinician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_staff', to='mis.clinician'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medications',
            field=models.ManyToManyField(blank=True, to='mis.medication'),
        ),
    ]
