# Generated by Django 4.0.5 on 2022-06-22 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0004_alter_patient_clinicians'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_details', to='mis.clinician'),
        ),
    ]
