# Generated by Django 4.0.5 on 2022-06-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0007_alter_appointment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='role',
            field=models.TextField(choices=[('C', 'Consultant'), ('D', 'Doctor'), ('N', 'Nurse'), ('S', 'Surgeon'), ('T', 'Therapist')], default='D', max_length=1),
            preserve_default=False,
        ),
    ]
