# Generated by Django 4.0.5 on 2022-06-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0009_medication_is_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='is_prescription',
            new_name='prescription_required',
        ),
    ]
