# Generated by Django 4.0.5 on 2022-06-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0010_rename_is_prescription_medication_prescription_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default='2022-06-22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
    ]
