# Generated by Django 4.0.5 on 2022-06-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0011_remove_appointment_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attended',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
