# Generated by Django 4.0.5 on 2022-06-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0013_remove_patient_appointments_patient_appointments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='appointments',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='notes',
        ),
    ]
