# Generated by Django 4.0.5 on 2022-06-29 16:48

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0014_remove_patient_appointments_remove_patient_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', '-time']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='first', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='last', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='roleCol',
            field=colorful.fields.RGBColorField(colors=['#aa2a2c'], default='#aa2a2c'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='roleCol',
            field=colorful.fields.RGBColorField(colors=['#2A6CAA', '#2aaa68']),
        ),
    ]
