# Generated by Django 4.0.5 on 2022-07-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0016_remove_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_clinician',
            field=models.BooleanField(default=False),
        ),
    ]
